FROM python:3.7

COPY ./basic-requirements.txt ./requirements.txt

RUN python -m pip install -r requirements.txt

COPY ./web/ ./
COPY ./utils/ ./

EXPOSE 8080

CMD gunicorn app:app --workers 1 --threads 1 --timeout 30000 -k uvicorn.workers.UvicornH11Worker -b 0.0.0.0:8080