FROM python:3.7

COPY ./requirements.txt ./requirements.txt

RUN python -m pip install -r requirements.txt

COPY ./ ./

EXPOSE 8080

CMD gunicorn app:app --workers 1 --threads 1 --timeout 30000 -k uvicorn.workers.UvicornH11Worker -b 0.0.0.0:8080